# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'init.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main_Dialog(object):
    def setupUi(self, main_Dialog):
        main_Dialog.setObjectName("main_Dialog")
        main_Dialog.resize(640, 480)
        self.insert_xinxi = QtWidgets.QPushButton(main_Dialog)
        self.insert_xinxi.setGeometry(QtCore.QRect(90, 100, 161, 111))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.insert_xinxi.setFont(font)
        self.insert_xinxi.setObjectName("insert_xinxi")
        self.select_data = QtWidgets.QPushButton(main_Dialog)
        self.select_data.setGeometry(QtCore.QRect(310, 100, 191, 111))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.select_data.setFont(font)
        self.select_data.setObjectName("select_data")
        self.update_data = QtWidgets.QPushButton(main_Dialog)
        self.update_data.setGeometry(QtCore.QRect(90, 260, 161, 101))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.update_data.setFont(font)
        self.update_data.setObjectName("update_data")
        self.delete_2 = QtWidgets.QPushButton(main_Dialog)
        self.delete_2.setGeometry(QtCore.QRect(320, 260, 181, 101))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.delete_2.setFont(font)
        self.delete_2.setObjectName("delete_2")
        self.exit = QtWidgets.QPushButton(main_Dialog)
        self.exit.setGeometry(QtCore.QRect(200, 390, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.exit.setFont(font)
        self.exit.setObjectName("exit")
        self.label = QtWidgets.QLabel(main_Dialog)
        self.label.setGeometry(QtCore.QRect(150, 30, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(main_Dialog)
        QtCore.QMetaObject.connectSlotsByName(main_Dialog)

    def retranslateUi(self, main_Dialog):
        _translate = QtCore.QCoreApplication.translate
        main_Dialog.setWindowTitle(_translate("main_Dialog", "Dialog"))
        self.insert_xinxi.setText(_translate("main_Dialog", "信息录入"))
        self.select_data.setText(_translate("main_Dialog", "信息查询"))
        self.update_data.setText(_translate("main_Dialog", "信息更新"))
        self.delete_2.setText(_translate("main_Dialog", "信息删除"))
        self.exit.setText(_translate("main_Dialog", "退出系统"))
        self.label.setText(_translate("main_Dialog", "李畅超学生信息管理系统"))
