# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'insert_message.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_insert_Dialog(object):
    def setupUi(self, insert_Dialog):
        insert_Dialog.setObjectName("insert_Dialog")
        insert_Dialog.resize(478, 385)
        self.label = QtWidgets.QLabel(insert_Dialog)
        self.label.setGeometry(QtCore.QRect(60, 20, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(insert_Dialog)
        self.label_2.setGeometry(QtCore.QRect(60, 70, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(insert_Dialog)
        self.label_3.setGeometry(QtCore.QRect(60, 120, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(insert_Dialog)
        self.label_4.setGeometry(QtCore.QRect(60, 170, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(insert_Dialog)
        self.label_5.setGeometry(QtCore.QRect(60, 220, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(insert_Dialog)
        self.label_6.setGeometry(QtCore.QRect(60, 270, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.id = QtWidgets.QLineEdit(insert_Dialog)
        self.id.setGeometry(QtCore.QRect(130, 30, 271, 21))
        self.id.setObjectName("id")
        self.name = QtWidgets.QLineEdit(insert_Dialog)
        self.name.setGeometry(QtCore.QRect(130, 80, 271, 21))
        self.name.setObjectName("name")
        self.sex = QtWidgets.QLineEdit(insert_Dialog)
        self.sex.setGeometry(QtCore.QRect(130, 130, 271, 21))
        self.sex.setObjectName("sex")
        self.adress = QtWidgets.QLineEdit(insert_Dialog)
        self.adress.setGeometry(QtCore.QRect(130, 180, 271, 21))
        self.adress.setObjectName("adress")
        self.phone = QtWidgets.QLineEdit(insert_Dialog)
        self.phone.setGeometry(QtCore.QRect(130, 230, 271, 21))
        self.phone.setObjectName("phone")
        self.major = QtWidgets.QLineEdit(insert_Dialog)
        self.major.setGeometry(QtCore.QRect(130, 280, 271, 21))
        self.major.setObjectName("major")
        self.ok = QtWidgets.QPushButton(insert_Dialog)
        self.ok.setGeometry(QtCore.QRect(60, 330, 80, 31))
        self.ok.setObjectName("ok")
        self.clear_data = QtWidgets.QPushButton(insert_Dialog)
        self.clear_data.setGeometry(QtCore.QRect(200, 330, 80, 31))
        self.clear_data.setObjectName("clear_data")
        self.exit = QtWidgets.QPushButton(insert_Dialog)
        self.exit.setGeometry(QtCore.QRect(350, 330, 80, 31))
        self.exit.setObjectName("exit")

        self.retranslateUi(insert_Dialog)
        QtCore.QMetaObject.connectSlotsByName(insert_Dialog)

    def retranslateUi(self, insert_Dialog):
        _translate = QtCore.QCoreApplication.translate
        insert_Dialog.setWindowTitle(_translate("insert_Dialog", "Dialog"))
        self.label.setText(_translate("insert_Dialog", "学号"))
        self.label_2.setText(_translate("insert_Dialog", "姓名"))
        self.label_3.setText(_translate("insert_Dialog", "性别"))
        self.label_4.setText(_translate("insert_Dialog", "地址"))
        self.label_5.setText(_translate("insert_Dialog", "电话"))
        self.label_6.setText(_translate("insert_Dialog", "专业"))
        self.ok.setText(_translate("insert_Dialog", "确定"))
        self.clear_data.setText(_translate("insert_Dialog", "重置"))
        self.exit.setText(_translate("insert_Dialog", "退出"))
