# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'success.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_su_Dialog(object):
    def setupUi(self, su_Dialog):
        su_Dialog.setObjectName("su_Dialog")
        su_Dialog.resize(442, 239)
        font = QtGui.QFont()
        font.setPointSize(15)
        su_Dialog.setFont(font)
        self.label = QtWidgets.QLabel(su_Dialog)
        self.label.setGeometry(QtCore.QRect(110, 30, 181, 101))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.exit = QtWidgets.QPushButton(su_Dialog)
        self.exit.setGeometry(QtCore.QRect(110, 150, 161, 51))
        self.exit.setObjectName("exit")

        self.retranslateUi(su_Dialog)
        QtCore.QMetaObject.connectSlotsByName(su_Dialog)

    def retranslateUi(self, su_Dialog):
        _translate = QtCore.QCoreApplication.translate
        su_Dialog.setWindowTitle(_translate("su_Dialog", "Dialog"))
        self.label.setText(_translate("su_Dialog", "操作成功"))
        self.exit.setText(_translate("su_Dialog", "确定"))
